name: Cleanup old branches
on:
  schedule:
    - cron: "0 0 * * 1" # every Monday at midnight
jobs:
  housekeeping:
    name: Cleanup old branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run delete-old-branches-action
        uses: beatlabs/delete-old-branches-action@v0.0.11
        with:
          repo_token: ${{ github.token }}
          date: "6 months ago"
          dry_run: true
          delete_tags: true
          extra_protected_branch_regex: ^(main)$
          extra_protected_tag_regex: "^v.*"
          exclude_open_pr_branches: true
